#!/usr/bin/env bash
# Proves two nozzle-engine builds are equivalent: identical --schema output and identical G-code (ignoring the
# generation timestamp) for the test cube on every listed printer profile.
# Usage: equivalence.sh REFERENCE_ENGINE CANDIDATE_ENGINE [profile id ...]   (default: every bundled profile pack)
set -uo pipefail
REF="$1"; CAND="$2"; shift 2
NOZZLE_ROOT="${NOZZLE_ROOT:-/mnt/faststorage/Nozzle It All}"
PACKS="$NOZZLE_ROOT/app/src/main/assets/slicer_profiles"; CUBE="$NOZZLE_ROOT/site-src/assets/test-cube-20mm.stl"
IDS=("$@"); [ ${#IDS[@]} -gt 0 ] || mapfile -t IDS < <(ls "$PACKS" | while read -r d; do [ -f "$PACKS/$d/machine.json" ] && echo "$d"; done)
# Profiles may call random() in custom G-code; a fixed seed makes both engines draw the same numbers.
export NOZZLE_GCODE_RANDOM_SEED="${NOZZLE_GCODE_RANDOM_SEED:-1}"
JOB="$(mktemp -d)"; trap 'rm -rf "$JOB"' EXIT
fail=0
if diff <("$REF" --schema) <("$CAND" --schema) > "$JOB/schema.diff"; then echo "schema: identical"; else echo "schema: DIFFERS"; head -20 "$JOB/schema.diff"; fail=1; fi
same=0; differ=0; bothfail=0; onefail=0
for id in "${IDS[@]}"; do
  d="$PACKS/$id"
  for which in ref cand; do
    printf 'out\t%s\nprofile\t%s\nprofile\t%s\nprofile\t%s\nset\tlayer_height\t0.2\nset\tsparse_infill_density\t15%%\nobject\t%s\t0\t0\t0\t1\t0\n' \
      "$JOB/$id.$which.gcode" "$d/machine.json" "$d/process.json" "$d/filament.json" "$CUBE" > "$JOB/$id.$which.txt"
  done
  "$REF" "$JOB/$id.ref.txt" >/dev/null 2>&1; r=$?
  "$CAND" "$JOB/$id.cand.txt" >/dev/null 2>&1; c=$?
  if [ $r -ne 0 ] && [ $c -ne 0 ]; then bothfail=$((bothfail+1)); continue; fi
  if [ $r -ne $c ]; then onefail=$((onefail+1)); echo "$id: exit ref=$r cand=$c"; fail=1; continue; fi
  filt() { grep -v -E '^; (generated by|HEADER_BLOCK|model label id|thumbnail)' "$1" | grep -v -i 'generated'; }
  if cmp -s <(filt "$JOB/$id.ref.gcode") <(filt "$JOB/$id.cand.gcode"); then
    same=$((same+1))
  else
    differ=$((differ+1)); fail=1
    diff <(filt "$JOB/$id.ref.gcode") <(filt "$JOB/$id.cand.gcode") > "$JOB/$id.diff" || true
    echo "$id: G-code differs ($(grep -c '^[<>]' "$JOB/$id.diff") lines), first:"
    grep '^[<>]' "$JOB/$id.diff" | head -4 | cut -c1-200 | sed 's/^/    /'
  fi
done
echo "profiles: ${#IDS[@]}  identical: $same  differ: $differ  both-fail: $bothfail  one-fails: $onefail"
exit $fail
