#!/usr/bin/env bash
# Golden output check: slices the 20 mm test cube on every printer profile bundled with Nozzle It All and compares a
# SHA-256 of each G-code (header timestamps removed) plus the settings schema with tools/nozzle/golden/outputs.sha256.
# A commit that changes output on purpose runs this with --update and commits the new file, so its diff lists exactly
# which printers' G-code changed.
# Usage: golden.sh ENGINE [--update]
set -uo pipefail
ENGINE="$1"; UPDATE="${2:-}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GOLDEN="$ROOT/tools/nozzle/golden/outputs.sha256"
NOZZLE_ROOT="${NOZZLE_ROOT:-/mnt/faststorage/Nozzle It All}"
PACKS="$NOZZLE_ROOT/app/src/main/assets/slicer_profiles"; CUBE="$NOZZLE_ROOT/site-src/assets/test-cube-20mm.stl"
export NOZZLE_GCODE_RANDOM_SEED="${NOZZLE_GCODE_RANDOM_SEED:-1}"
JOB="$(mktemp -d)"; trap 'rm -rf "$JOB"' EXIT

one() {
  local id="$1" d="$PACKS/$1"
  printf 'out\t%s\nprofile\t%s\nprofile\t%s\nprofile\t%s\nset\tlayer_height\t0.2\nset\tsparse_infill_density\t15%%\nobject\t%s\t0\t0\t0\t1\t0\n' \
    "$JOB/$id.gcode" "$d/machine.json" "$d/process.json" "$d/filament.json" "$CUBE" > "$JOB/$id.txt"
  if "$ENGINE" "$JOB/$id.txt" >/dev/null 2>&1; then
    printf '%s %s\n' "$(grep -v -E '^; (generated by|HEADER_BLOCK|model label id|thumbnail)' "$JOB/$id.gcode" | grep -v -i 'generated' | sha256sum | cut -c1-64)" "$id"
  else
    printf '%s %s\n' "slice-failed" "$id"
  fi
  rm -f "$JOB/$id.gcode"
}
export -f one; export ENGINE JOB PACKS CUBE

{
  printf '%s %s\n' "$("$ENGINE" --schema 2>/dev/null | sha256sum | cut -c1-64)" "(settings-schema)"
  ls "$PACKS" | while read -r d; do [ -f "$PACKS/$d/machine.json" ] && echo "$d"; done |
    xargs -P "${GOLDEN_JOBS:-8}" -I{} bash -c 'one "$@"' _ {} | sort -k2
} > "$JOB/current"

if [ "$UPDATE" = "--update" ]; then
  mkdir -p "$(dirname "$GOLDEN")"; cp "$JOB/current" "$GOLDEN"
  echo "updated $GOLDEN ($(wc -l < "$GOLDEN") entries)"; exit 0
fi
if diff -u "$GOLDEN" "$JOB/current" > "$JOB/diff"; then
  echo "golden: all $(wc -l < "$GOLDEN") outputs match"; exit 0
fi
echo "golden: outputs differ from tools/nozzle/golden/outputs.sha256:"
grep '^[-+][^-+]' "$JOB/diff" | sed 's/^/  /'
echo "If the change is intended, run tools/nozzle/golden.sh <engine> --update and commit the file with the reason."
exit 1
